language: php

php:
  - '5.5.9'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - echo "\n" | pecl install pdo_sqlite
  - echo "\n" | pecl install fileinfo
  - echo "\n" | pecl install imagick
  - composer self-update
  - npm install -g npm@2
  - export COMPOSER_PROCESS_TIMEOUT=600
  - composer rebuild

script:
  - composer test
